version: '3.9'

services:
  postgres:
    image: postgres:12-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: bookstore
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data
    networks:
      - bookstore-network

  nestjs-app:
    build: ./nest-be
    ports:
      - 4000:4000
    depends_on:
      - postgres
    networks:
      - bookstore-network
  
  nextjs-app:
    build: ./next-fe
    ports:
      - 3000:3000
    depends_on:
      - nestjs-app
    environment:
      NEXT_PUBLIC_API_URL: http://nestjs-app:3000
    networks:
      - bookstore-network

volumes:
  postgresql_data:

networks:
  bookstore-network:
    driver: bridge